version: '3'

services:

    php: &php
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        restart: always
        volumes:
            - ./:/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        env_file:
            - .env
        working_dir: /www

    postgres:
        image: postgres:14.3-alpine3.15
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./pg-dumps:/pg-dumps
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

volumes:
    postgres-data:
